### ISSUE TITLE
KeyError: 'fiducials'

### ISSUE THREAD

**Issue by Yadunund** [osrf/traffic_editor#87]
Error when running `building_map_gazebo`  and `building_map_nav` on [existing maps](https://github.com/osrf/rmf_demos/tree/feature/caddy/rmf_demo_maps) following merge of #85 .

Error details:
```
Starting >>> rmf_demo_maps
--- stderr: rmf_demo_maps
Traceback (most recent call last):
  File "/home/rmf_demos_ws/install/building_map_tools/lib/building_map_tools/building_map_gazebo", line 11, in <module>
    load_entry_point('building-map-tools==0.0.0', 'console_scripts', 'building_map_gazebo')()
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map_generators/building_map_gazebo.py", line 20, in main
    options)
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map/generator.py", line 56, in generate_gazebo_sdf
    options + ['gazebo'])
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map/generator.py", line 29, in generate_sdf
    building = self.parse_editor_yaml(input_filename)
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map/generator.py", line 18, in parse_editor_yaml
    return Building(y)
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map/building.py", line 18, in __init__
    self.levels[level_name] = Level(level_yaml, level_name)
  File "/home/rmf_demos_ws/install/building_map_tools/lib/python3.6/site-packages/building_map/level.py", line 46, in __init__
    if yaml_node['fiducials']:
KeyError: 'fiducials
```

**Comment by Yadunund** [comment]
This has been resolved by #86 .
